const QUESTIONS = [
  { id: 'name', label: 'Your Name', type: 'text', placeholder: 'Type your name…' },
  { id: 'howWeMet', label: 'How did we first meet?', type: 'textarea', placeholder: 'Take me back to that moment…' },
  { id: 'firstImpression', label: 'What was your first impression of me?', type: 'textarea', placeholder: 'Be honest…' },
  { id: 'threeWords', label: 'Describe me in three words — and why.', type: 'textarea', placeholder: 'Three words, and the story behind them…' },
  { id: 'favoriteMemory', label: 'What\u2019s your favorite memory of us?', type: 'textarea', placeholder: 'The one you replay in your head…' },
  { id: 'biggestStrength', label: 'What\u2019s my biggest strength?', type: 'textarea', placeholder: 'What do I do best, in your eyes?' },
  { id: 'shouldImprove', label: 'What\u2019s one thing I should improve?', type: 'textarea', placeholder: 'I can take it — go ahead…' },
  { id: 'notNoticed', label: 'What\u2019s something about me that most people don\u2019t notice?', type: 'textarea', placeholder: 'The quiet detail only you\u2019ve caught…' },
  { id: 'helpedInspired', label: 'Have I ever helped or inspired you? Tell me how.', type: 'textarea', placeholder: 'A moment I might not even remember…' },
  { id: 'funniestMemory', label: 'What\u2019s the funniest memory we share?', type: 'textarea', placeholder: 'The one that still makes you laugh…' },
  { id: 'songReminder', label: 'Which song reminds you of me, and why?', type: 'text', placeholder: 'Song title — and the reason' },
  { id: 'movieTitle', label: 'If our friendship were a movie, what would its title be?', type: 'text', placeholder: 'Give it a title…' },
  { id: 'questionToAsk', label: 'What\u2019s one question you\u2019ve always wanted to ask me?', type: 'textarea', placeholder: 'Now\u2019s your chance…' },
  { id: 'changeOneThing', label: 'If you could change one thing about our friendship, what would it be?', type: 'textarea', placeholder: 'Honesty makes it stronger…' },
  { id: 'fiveYears', label: 'Where do you think I\u2019ll be in five years?', type: 'textarea', placeholder: 'Paint the picture…' },
  { id: 'alwaysWantedToTell', label: 'What\u2019s something you\u2019ve always wanted to tell me?', type: 'textarea', placeholder: 'Say it here…' },
  { id: 'advice', label: 'What\u2019s one piece of advice you\u2019d give me?', type: 'textarea', placeholder: 'What do you want me to know?' },
  { id: 'neverChange', label: 'What\u2019s one thing you hope I never change?', type: 'text', placeholder: 'The thing that makes me, me…' },
  { id: 'memoryToKeep', label: 'What\u2019s one memory of me you\u2019ll always keep?', type: 'textarea', placeholder: 'The one you\u2019ll carry forward…' },
  { id: 'heartfeltMessage', label: 'Leave me a heartfelt message that I\u2019ll remember for years.', type: 'textarea', placeholder: 'This is the one I\u2019ll read again and again…' },
];
